### ISSUE TITLE
Palavras com acento?

### ISSUE THREAD

**Issue by caroubauer** [vassourita/twitter-bot-template#1]
Oi, primeiramente, queria agradecer o código, tem nos ajudado muito em uma pesquisa de Humanidades Digitais. Com ele, criamos o Buppa (@buppabot). Porém, estou com um problema: preciso que o bot retuíte "bicentenário" (com e sem acento). Isso é possível? Coloquei esses dois termos no código, mas ele não está retuitando o termo acentuado... Obrigada!

**Comment by vassourita** [comment]
As we discussed privately, this was just a mistake caused by a space left over between the words to be tracked. I'll add a .trim() on each word to prevent this from happening to other people. Thank you for contacting me, this was a possibility that I didn't foresee
